### ISSUE TITLE
does not validate correct for country tlds (com.au)

### ISSUE THREAD

**Issue by pixelpaulaus** [miguelmota/is-valid-domain#11]
if i were to test

`google.com"\'\"\""\\"\\'test test`

it comes back as invalid

it i test:

`google.com.au'"\'\"\""\\"\\'test`

it comes back as valid

**Comment by miguelmota** [comment]
@pixelpaulaus wow that's a terrible bug. It's fixed now in the latest release. Thanks for reporting!
