### ISSUE TITLE
Underscore in domain name

### ISSUE THREAD

**Issue by radziszp** [miguelmota/is-valid-domain#13]
Hello,
it seems to be valid to have underscores in subdomain name like `_underscore.hello.com`
https://ubuntu101.co.za/dns-and-bind/underscores-domain-names-do-they-work/
But this library returns false.

I have domain `xn--_eamop-.donata.com` (name has been anonymized), that https://who.is/dns/{original name} returns valid data, so domain is valid too

**Comment by miguelmota** [comment]
Hi, thank you for reporting this bug. It's now resolved in the latest released.
