### ISSUE TITLE
"isValidDomain('www.example.com', {wildcard: true})" should be false

### ISSUE THREAD

**Issue by wuhonglei** [miguelmota/is-valid-domain#16]
In my opinion, domain must has wildcard when wildcard set to true, but the result is not that, as follow code.
```javascript
isValidDomain('www.example.com', {wildcard: true}); // the result is true
```

**Comment by pierreminik** [comment]
Doesn't make any sense in my opinion. The library is to check if a given domain is valid, not if they are a specific type of domain.

Even so, If this was to be implemented it would break backwards compatibility so that's really a bad idea.

**Comment by miguelmota** [comment]
The `wildcard` and `subdomain` options are to allow wildcards and subdomains respectively but it doesn't require them in order to validate as true. Maybe an additional `requireWildcard` option makes more sense?
