### ISSUE TITLE
Subdomain that ends with a dot is valid

### ISSUE THREAD

**Issue by jaranst** [miguelmota/is-valid-domain#18]
When a domain ends with a dot, and subdomain flag is set to false, it still returns as valid:

```node
isValidDomain('example.com.', { subdomain: false } // returns true
```

Is this the correct behavior?

**Comment by shlevy** [comment]
This is correct: http://www.dns-sd.org/trailingdotsindomainnames.html

**Comment by miguelmota** [comment]
It's expected behavior as @shlevy pointed out. Closing.
