### ISSUE TITLE
Allow protocols http:// and https:// ftp:// etc

### ISSUE THREAD

**Issue by HappyLDE** [miguelmota/is-valid-domain#19]
Maybe add in the possibility to allow protocols with a list like:

`isValidDomain('https://domain.tld', { allowedProtocols: ['https'] })`

What do you think?

**Comment by miguelmota** [comment]
I think that's better suited for a separate package and it's also trivial do it with regex.
For example:

```js
let value = 'http://example.com'
let match = value.match(/^(https|ftp):\/\/([0-9a-z.-_]+)$/)
if (match && isValidDomain(match[2])) {
  // valid
}
```

The plan is to keep the functionality of this package as simple as possible.
