### ISSUE TITLE
punnycode with hypen

### ISSUE THREAD

**Issue by askurihin** [miguelmota/is-valid-domain#22]
Hello!

Thank you for this library.

I found a small bug - this should be a valid domain name:
привет-мир.рф -> xn----ctbjkdxqigq.xn--p1ai 

```js
> isValidDomain('xn----ctbjkdxqigq.xn--p1ai')
false
```

**Comment by brendonjohn** [comment]
I was having a look at this. These were my findings

```
isValidDomain('привет-мир.рф', { allowUnicode: true })             // false
isValidDomain('test-me.рф', { allowUnicode: true })                // true
isValidDomain('приветмир.com', { allowUnicode: true })             // true
isValidDomain('xn--b1aghctohfp.xn--p1ai', { allowUnicode: false }) // true
isValidDomain('привет-мир.com', { allowUnicode: true })            // false
isValidDomain('test--me.рф', { allowUnicode: true })               // false
```

We can see the TLD `рф` is fine, but the domain name `привет-мир` is not.

> The Unicode string MUST NOT contain "--" (two consecutive hyphens) in
> the third and fourth character positions and MUST NOT start or end
> with a "-" (hyphen).

The domain name is failing from trying to enforce the "hyphen restrictions" in [rfc5891](https://datatracker.ietf.org/doc/html/rfc5891#section-4.2.3.1).

**Comment by evgencode** [comment]
The same. 
Domains like: привет-мир.рф, дядя-ваня.рф etc - return false

```
const isValidDomain = require("is-valid-domain");
const punycode = require('punycode');

console.log(isValidDomain(punycode.toASCII(host)));
```

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/is-valid-domain/pull/27
