### ISSUE TITLE
TLDs not supported

### ISSUE THREAD

**Issue by MattIPv4** [miguelmota/is-valid-domain#23]
This library doesn't appear to detect a TLD as a valid domain, even though they are -- it would be great if this was supported, either by default or with a flag.

Currently:

```
const isValidDomain = require('is-valid-domain')

console.log(isValidDomain('test.ai.')) // true
console.log(isValidDomain('ai.')) // false
```

But http://ai./ is valid.

**Comment by flotwig** [comment]
In a similar vein, it would be nice if you this supported not just TLDs, but hostnames as well, so `isValidDomain('localhost')` would be true.

**Comment by miguelmota** [comment]
@MattIPv4 Thanks for bringing this up. An option might be better to prevent breaking changes. Let me know if you have any suggestions on the option name.

**Comment by miguelmota** [comment]
@flotwig The llibrary [`is-valid-hostname`](https://github.com/miguelmota/is-valid-hostname) might help in this case

**Comment by MattIPv4** [comment]
> Let me know if you have any suggestions on the option name.

Maybe `topLevel` to somewhat match the existing flags, or if less worried about matching, maybe `tldsValid`?

**Comment by miguelmota** [comment]
@MattIPv4 The newest version has the option now

```js
isValidDomain('ai.') // false
isValidDomain('ai.', {topLevel: true}) // true
```

It'll validate country code TLDs based on [ISO_3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

We'll come up with more descriptive option names on the next major release in the future. 

Let me know if you run into any problems.

Thanks!

Closed by https://github.com/miguelmota/is-valid-domain/commit/db70f4abf7417adcdab9551ebf84f0686aec3ae2

**Comment by MattIPv4** [comment]
Tyvm, works great!

It looks like the typings weren't updated for this new opt?

**Comment by miguelmota** [comment]
@MattIPv4 should be updated now! thanks again

**Comment by mikestopcontinues** [comment]
Shouldn't other TLDs return true with `topLevel`? E.G. `com.`, `net.`, etc.?
