### ISSUE TITLE
"isValidDomain('dfgdfg.dfgdf33.e', {subdomain: true})" should be false

### ISSUE THREAD

**Issue by ryaa** [miguelmota/is-valid-domain#30]
It returns true - see below
![Screen Shot 2022-03-15 at 08 43 49](https://user-images.githubusercontent.com/3608222/158314521-1aed938e-8438-4793-b809-9cc2971cca96.png)

The below must also return false
![Screen Shot 2022-03-15 at 08 44 29](https://user-images.githubusercontent.com/3608222/158314577-fec36831-d35e-49a5-a53f-dced803c6b9a.png)
![Screen Shot 2022-03-15 at 08 46 54](https://user-images.githubusercontent.com/3608222/158314851-8cc0328b-db9e-4cc7-bb65-50fb1bb2103f.png)

**Comment by miguelmota** [comment]
Closing as this is expected behavior
