### ISSUE TITLE
Support Typescript import

### ISSUE THREAD

**Issue by imsamdez** [miguelmota/is-valid-domain#32]
Hey,

Love this package and was using the 0.0.17 version in my typescript project.
But since 0.1.6, i'm not able to import it correctly (no matters the way, default or single).

<img width="807" alt="Capture d’écran 2022-06-30 à 01 17 19" src="https://user-images.githubusercontent.com/22425976/176599111-55e4b761-7fdd-468f-895c-74b9ff37e259.png">

Do you plan to support it again ?
Thanks!

**Comment by jameswest368** [comment]
`import isValidDomain from "is-valid-domain";`

![is-valid-domain](https://user-images.githubusercontent.com/108466793/180170866-c63118ac-c9e0-44d5-a23e-2f689bf905fa.jpg)

**Comment by miguelmota** [comment]
as @jameswest368 suggested,

instead of importing as

```ts
import * as isValidDomain from 'is-valid-domain'
```

do

```ts
import isValidDomain from 'is-valid-domain'
```

and it should work
