### ISSUE TITLE
Validation without subdomain should validate .co.uk domains

### ISSUE THREAD

**Issue by Jerome1337** [miguelmota/is-valid-domain#9]
When I try to validate a domain name without subdomain is work for most of domains but fail with composed TLD (co.uk ...)

For example:

```
isValidDomain('www.domain.com', {
  subdomain: false,
}); // false

isValidDomain('domain.co.uk', {
  subdomain: false,
}); // false
```

The second case should be true instead of false.

**Comment by miguelmota** [comment]
@Jerome1337 thanks for reporting. Pushed a fix in the latest release that checks for second level domains. Thanks!
